# Regresión y evaluación de hipótesis
---

Regression es un tipo de  algoritmo de machine learning que se usa para predecir una categoria.
* Neural network regression
* Decision tree regression
* LASSO regression
* Ridge regression
* ElasticNet regression

In [1]:
import pandas as pd
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()

In [2]:
data = pd.DataFrame(iris.data)
data.columns = iris.feature_names
data['target'] = iris.target
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## Asignando su respectivo nombre de acuerdo al target

In [7]:
data['names'] = data['target'].map(
    {
        0: 'setosa',
        1: 'versicolor',
        2: 'virginica'
    }
)
data.head(4)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   

   target   names  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa

In [11]:
from sklearn.model_selection import train_test_split

target_column = ['target', 'names']
descritores = list(set(list(data.columns))-set(target_column))
descritores

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [17]:
X = data[descritores].values
Y = data['target'].values

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=40)


In [21]:
from sklearn.tree import DecisionTreeRegressor

# Escogemos el modelo
regr_1 = DecisionTreeRegressor(max_depth=4)
# Ajustar a los datos de entrenamiento
regr_1.fit(X_train, Y_train)
# Vamos a predecir que tanbien lo esta haciendo
predict_train = regr_1.predict(X_train)
predict_test = regr_1.predict(X_test)

## Metricas de evaluacion
- **recall**: es la sensibilidad
- **f1-score**: El promedio ponderado entre la precision y la exactitud 

En este caso sale un puntaje perfecto, porque es un data set de entrenamiento, pero en la vida real siempre tendran un valor mas bajo.

In [27]:
from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(Y_test, predict_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        15

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



0: 'setosa',
1: 'versicolor',
2: 'virginica'
        
Nos esta indicando cuantos positivos los esta haciendo bien. Cuando los valores que estan en la diagonal sus valores a costados son igual a cero lo esta haciendo muy bien. Pero Si observamos que tienen otros valores puede significar que tiene un falso positivo o un falso negativo. Y nos esta indicado en que variable lo esta haciendo mal.

In [30]:
print(confusion_matrix(Y_test, predict_test))

[[16  0  0]
 [ 0 14  0]
 [ 0  0 15]]
